services:
  zwave-js-ui:
    image: zwavejs/zwave-js-ui:latest
    container_name: zwave-js-ui
    # restart: unless-stopped
    restart: no

    devices:
      - /dev/ttyACM0:/dev/ttyACM0

    tty: true
    stop_signal: SIGINT

    environment:
      TZ: Europe/Berlin

    volumes:
      - ./store:/usr/src/app/store
      - ./logs:/usr/src/app/logs

    ports:
      - "8091:8091"

    depends_on:
      - mosquitto

    networks:
      - zwave-net


  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    # restart: unless-stopped
    restart: no

    ports:
      - "1883:1883"

    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

    networks:
      - zwave-net


networks:
  zwave-net:
    external: true
